# Generated by Django 4.0.4 on 2022-05-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0002_player_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='player_id',
            new_name='player',
        ),
    ]
