# Generated by Django 4.0.4 on 2022-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0005_alter_rating_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
    ]
